### PR TITLE
Delete Tasks

### LINKED ISSUE #16: Task Deletion Function

### PR DESCRIPTION
**Pull request by JasonWarrenUK**
- Gave to do list header same styles as list items
- removed dark mode
- added debug styles so we can see what's misbehaving
- replaced iconTick (which doesn't exist in CSS) with tick-container

Closes #16

### CODE REVIEW

**Review by Frannerz — APPROVED** [review]

**Review by Frannerz — COMMENTED** [review]
I think if you remove .iconTicks that is going to stop the 'complete task' function from running properly as I have used a query selector for that class

**Comment by JasonWarrenUK** [comment]
Can we change it so that it queries something else (like an image within a tick-container)?

Any time I do non-standard CSS, like making classes that only apply to one item rather than just using id, or creating classes that don't do anything in CSS, a huge amount of the feedback and advice becomes about that

**Comment by Frannerz** [comment]
It doesn't only apply to one item, it applies to each task that is generated which is why I haven't used id. But feel free to change the query to something else. As long as you check everything still works!

**Comment by JasonWarrenUK** [comment]
Oh sorry I didn't mean we should use id for this, what I meant was that if we use select the first image within a task rather than searching for that class, then i think it'll achieve the same thing. But I'll make sure it doesn't break before I push!

**Comment by Frannerz** [comment]
Hiya, I haven't merged this yet as it looks like some of the functions have been deleted in JS? I will have a proper look when I'm home from work.

**Comment by JasonWarrenUK** [comment]
Nah it's all still there, if you're looking at it in a diff viewer then it might look like things are deleted but they've just moved further down the file because I've added debug elements

**Comment by Frannerz** [comment]
Cool just had another look and merged. Will have a proper look later. Well done!

**Pull request merged**
